name: 'Operator-SDK K8s Action'
description: 'GitHub Actions for Operator-SDK build'
author: 'Daniel Ramirez <dxas90@gmail.com>'
branding:
  icon: 'package'
  color: 'blue'
inputs:
  image:
    description: 'Image name'
    required: true
  tag:
    description: 'Image tag'
    required: false
  dirPath:
    description: 'Project structure requires build/Dockerfile'
    required: false
  args:
    description: 'Additional arguments passed to operator-sdk build'
    required: false
outputs:
  image:
    description: 'Built docker image name'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.image }}
    - ${{ inputs.tag }}
    - ${{ inputs.dirPath }}
    - ${{ inputs.args }}
